### ISSUE TITLE
Purge Cache

### ISSUE THREAD

**Issue by callumNE6** [rennokki/laravel-eloquent-query-cache#12]
First off, thanks so much for this!

I was just wondering if there's any means by which I can purge the cache entirely?

As an example use case:

- Data is cached for 1 week
- If new data is added (handled by one of the controllers), purge the cache once the new data is added, and this will then be cached for one week or until new data is added

**Comment by callumNE6** [comment]
My bad, just realised it's using Laravel's cache storage so I can just use Cache::flush()

**Comment by rennokki** [comment]
@callumNE6 You can clear the whole cache with Cache::flush() or use the built-in method flushQueryCache without arguments to clear the whole cache.

**Comment by apeisa** [comment]
For me it seems that flushQueryCache() doesn't work without tags at all: https://github.com/rennokki/laravel-eloquent-query-cache/blob/master/src/Traits/QueryCacheModule.php#L152

Am I right? There doesn't seem to be easy way to empty whole cache per model?

**Comment by rennokki** [comment]
https://github.com/rennokki/laravel-eloquent-query-cache/releases/tag/1.4.0
