### ISSUE TITLE
Impossible to flush cache without tags

### ISSUE THREAD

**Issue by apeisa** [rennokki/laravel-eloquent-query-cache#17]
For me it seems that flushQueryCache() doesn't work without tags at all: https://github.com/rennokki/laravel-eloquent-query-cache/blob/master/src/Traits/QueryCacheModule.php#L152

Am I right? There doesn't seem to be easy way to empty whole cache per model?

_Originally posted by @apeisa in https://github.com/rennokki/laravel-eloquent-query-cache/issues/12#issuecomment-612664909_

**Comment by rennokki** [comment]
You can set up an additional tag on each query and flush it by that tag:

```php
Post::cacheFor(60)
    ->cacheTags(['query', 'posts'])
    ->get();

Category::cacheFor(60)
    ->cacheTags(['query', 'categories'])
    ->get();

Post::flushQueryCache(['query']); // flushes both
```

Query Cache relies on the tags to invalidate the cache, making a distinction between the cached queries and your normal cache; otherwise you can call `cache:clear` to invalidate all the cache.

**Comment by rennokki** [comment]
Check this tag: https://github.com/rennokki/laravel-eloquent-query-cache/releases/tag/1.4.0

**Comment by apeisa** [comment]
Thanks, looks great! Does that implementation mean that this doesn't work at all with cache drivers that doesn't support tags?

**Comment by rennokki** [comment]
You have to "mark" each query. It would be a pain to invalidate queries giving the query string.
