### ISSUE TITLE
[Question] How to clear cache based on user or model id?

### ISSUE THREAD

**Issue by afiqiqmal** [rennokki/laravel-eloquent-query-cache#18]
How to flush for specific user after the user update profile? the only flush method is flushQueryCache() with clear all the caches in the same tags.

**Comment by ColaTasty** [comment]
Maybe u can set ```$user->id``` in tags when loading profile?

**Comment by umituz** [comment]
I could not find a source for this situation either. How can I solve this problem?

**Comment by rennokki** [comment]
The caching happens at the query level, way back before your actual models are retrieved and IDs are known. You have to specify the tags at the query level in case you want to retrieve some specific ID resource:

```php
User::cacheFor(60)
    ->cacheTags(['user:1'])
    ->find(1);
```
Later, you can invalidate it:

```php
User::flushQueryCache(['user:1']);
```

Alternatively, if you reside your query in a controller, you can pass the ID:

```php
public function show(Request $request, $id)
{
    User::cacheFor(60)
        ->cacheTags(["user:{$id}"])
        ->find($id);

    //
}
```

**Comment by rennokki** [comment]
PR: https://github.com/rennokki/laravel-eloquent-query-cache/pull/19
Tag: https://github.com/rennokki/laravel-eloquent-query-cache/releases/tag/1.4.0
